### PR TITLE
Update RobustToolbox to v0.2.11

### PR DESCRIPTION
**Pull request by 20kdc**
this handles the changes needed for XAML UI

### CODE REVIEW

**Comment by PaulRitter** [comment]
i think this also needs changes to the solution

**Comment by PaulRitter** [comment]
specifically, the following proj need to be added
ManagedHttpListener
System.Net.HttpListener
Robust.LoaderApi
XamlX
XamlX.IL.Cecil
XamlX.Runtime
OpenToolkit.GraphicsLibraryFramework
Robust.Client.Injectors
Robust.Client.NameGenerator

**Comment by 20kdc** [comment]
yeah... may I ask how to do that properly?

**Comment by PJB3005** [comment]
@20kdc do `dotnet sln add Path/To/Csproj.csproj` from the directory containing the main sln, for every project listed.

**Pull request merged**
